version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  winy:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: winy
    ports:
      - "8501:8501"
    depends_on:
      - qdrant
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  qdrant_data:
